import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

RESEND_API_KEY   = os.getenv("RESEND_API_KEY", "")
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
SMTP_HOST  = os.getenv("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT  = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER  = os.getenv("SMTP_USER", "")
SMTP_PASS  = os.getenv("SMTP_PASS", "")
FROM_EMAIL = os.getenv("FROM_EMAIL", "onboarding@resend.dev")
FROM_NAME  = os.getenv("FROM_NAME", "Rabbitt AI — Sales Insights")


def _build_html(summary: str, stats: dict) -> str:
    revenue = stats.get("total_revenue")
    units   = stats.get("total_units")
    rows    = stats.get("total_rows", 0)

    revenue_str = f"${revenue:,.0f}" if revenue is not None else "N/A"
    units_str   = f"{units:,}"       if units   is not None else "N/A"
    rows_str    = f"{rows:,}"

    paragraphs = ""
    for block in summary.split("\n\n"):
        block = block.strip()
        if not block:
            continue
        if block.startswith("#") or len(block) < 60:
            paragraphs += f'<h3 style="color:#1a1a2e;margin:24px 0 8px;">{block.lstrip("#").strip()}</h3>'
        else:
            paragraphs += f'<p style="margin:0 0 16px;line-height:1.7;">{block}</p>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Sales Insight Report</title></head>
<body style="font-family:'Segoe UI',Arial,sans-serif;background:#f4f6fb;margin:0;padding:0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6fb;padding:40px 0;">
    <tr><td align="center">
      <table width="620" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
        <tr>
          <td style="background:linear-gradient(135deg,#0f3460 0%,#16213e 100%);padding:36px 40px;">
            <p style="margin:0 0 4px;color:#e94560;font-size:11px;letter-spacing:3px;text-transform:uppercase;font-weight:700;">Rabbitt AI</p>
            <h1 style="margin:0;color:#ffffff;font-size:26px;font-weight:700;">Sales Insight Report</h1>
            <p style="margin:8px 0 0;color:#aab4c8;font-size:14px;">AI-Generated Executive Summary</p>
          </td>
        </tr>
        <tr>
          <td style="background:#0f3460;padding:0 40px 28px;">
            <table width="100%" cellpadding="0" cellspacing="0"><tr>
              <td style="background:rgba(255,255,255,0.08);border-radius:8px;padding:16px 20px;text-align:center;">
                <p style="margin:0;color:#aab4c8;font-size:11px;text-transform:uppercase;">Total Revenue</p>
                <p style="margin:4px 0 0;color:#fff;font-size:22px;font-weight:700;">{revenue_str}</p>
              </td>
              <td width="12"></td>
              <td style="background:rgba(255,255,255,0.08);border-radius:8px;padding:16px 20px;text-align:center;">
                <p style="margin:0;color:#aab4c8;font-size:11px;text-transform:uppercase;">Units Sold</p>
                <p style="margin:4px 0 0;color:#fff;font-size:22px;font-weight:700;">{units_str}</p>
              </td>
              <td width="12"></td>
              <td style="background:rgba(255,255,255,0.08);border-radius:8px;padding:16px 20px;text-align:center;">
                <p style="margin:0;color:#aab4c8;font-size:11px;text-transform:uppercase;">Records</p>
                <p style="margin:4px 0 0;color:#fff;font-size:22px;font-weight:700;">{rows_str}</p>
              </td>
            </tr></table>
          </td>
        </tr>
        <tr>
          <td style="padding:36px 40px;color:#333;font-size:15px;">{paragraphs}</td>
        </tr>
        <tr>
          <td style="background:#f8f9fc;padding:24px 40px;border-top:1px solid #e8ecf4;">
            <p style="margin:0;color:#8a94a6;font-size:12px;text-align:center;">
              Generated by <strong>Rabbitt AI — Sales Insight Automator</strong> &bull; Confidential
            </p>
          </td>
        </tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


async def send_email(recipient: str, subject: str, summary: str, stats: dict) -> None:
    """Send summary email. Priority: Resend → SendGrid → SMTP → demo mode."""
    html_body = _build_html(summary, stats)

    if RESEND_API_KEY:
        try:
            await _send_via_resend(recipient, subject, summary, html_body)
            logger.info(f"Email sent via Resend to {recipient}")
            return
        except Exception as e:
            logger.warning(f"Resend failed: {e} — trying next provider")

    if SENDGRID_API_KEY:
        try:
            await _send_via_sendgrid(recipient, subject, summary, html_body)
            logger.info(f"Email sent via SendGrid to {recipient}")
            return
        except Exception as e:
            logger.warning(f"SendGrid failed: {e} — trying SMTP fallback")

    if SMTP_USER and SMTP_PASS:
        _send_via_smtp(recipient, subject, summary, html_body)
        logger.info(f"Email sent via SMTP to {recipient}")
        return

    logger.warning(f"[DEMO MODE] No credentials set — would have emailed: {recipient}")
    logger.info(f"[DEMO MODE] Summary preview: {summary[:200]}")


async def _send_via_resend(recipient: str, subject: str, plain: str, html: str) -> None:
    import httpx
    payload = {
        "from":    f"{FROM_NAME} <{FROM_EMAIL}>",
        "to":      [recipient],
        "subject": subject,
        "text":    plain,
        "html":    html,
    }
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            "https://api.resend.com/emails",
            json=payload,
            headers={"Authorization": f"Bearer {RESEND_API_KEY}"},
        )
        resp.raise_for_status()


async def _send_via_sendgrid(recipient: str, subject: str, plain: str, html: str) -> None:
    import httpx
    payload = {
        "personalizations": [{"to": [{"email": recipient}]}],
        "from":    {"email": FROM_EMAIL, "name": FROM_NAME},
        "subject": subject,
        "content": [
            {"type": "text/plain", "value": plain},
            {"type": "text/html",  "value": html},
        ],
    }
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            "https://api.sendgrid.com/v3/mail/send",
            json=payload,
            headers={"Authorization": f"Bearer {SENDGRID_API_KEY}"},
        )
        resp.raise_for_status()


def _send_via_smtp(recipient: str, subject: str, plain: str, html: str) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"{FROM_NAME} <{FROM_EMAIL}>"
    msg["To"]      = recipient
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html,  "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.ehlo()
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(FROM_EMAIL, [recipient], msg.as_string())